version: '3'
services:

  #Node JS
  node-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_service
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local